import = ["~/.config/alacritty/catppuccin-frappe.toml",]

[font]
size = 9.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"  
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
opacity = 0.8
dimensions = { columns = 115, lines = 30 }

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
{ key = "S", mods = "Control|Alt", action = "Copy" },
{ key = "V", mods = "Control|Alt", action = "Paste" },
]


